### PR TITLE
Imap support

### PR DESCRIPTION
**Pull request by j0ack**
I've done the revert work mentioned here #221 to be allow to use our own SMTP server.

Since this work seems old let me know if this PR is outdated and what I can do to be able to merge this functionality.

### CODE REVIEW

**Comment by arjhun** [comment]
Ah, So close! I don't have the knowledge to fix this pull request, but I would very much like to use this feature! Could somebody look at merging this? Thanks in advance!

**Comment by scott** [comment]
Hi @arjhun and @j0ack I am going to take a look at this to see if I can get it running :)

**Comment by arjhun** [comment]
Thanks Scott! Very much appreciated!

**Comment by scott** [comment]
@arjhun I got a PR #810 and verified its working on my localhost with gmail as the IMAP host.  Had to allow insecure apps in gmail though which is not ideal.  Would love if you wanted to merge this to your branch and give it a try!

**Comment by arjhun** [comment]
hi scott,

Sorry for not getting back on this sooner. I'm getting this issue starting the rake task:

`SocketError: getaddrinfo: Servname not supported for ai_socktype`.

It worked before. I tried to debug but to no avail.

```
** Invoke helpy:mailman (first_time)
** Invoke environment (first_time)
** Execute environment
fatal: bad default revision 'HEAD'
** Execute helpy:mailman
imap config found
I, [2018-05-07T18:05:45.493519 #25792]  INFO -- : Mailman v0.7.3 started
I, [2018-05-07T18:05:45.493974 #25792]  INFO -- : IMAP receiver enabled (####@####.###@imap.gmail.com).
I, [2018-05-07T18:05:45.611021 #25792]  INFO -- : Polling disabled. Checking for messages once.
rake aborted!
SocketError: getaddrinfo: Servname not supported for ai_socktype
/home/arjen/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/imap.rb:1082:in `initialize'
/home/arjen/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/imap.rb:1082:in `open'
/home/arjen/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/imap.rb:1082:in `initialize'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/mailman-0.7.3/lib/mailman/receiver/imap.rb:49:in `new'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/mailman-0.7.3/lib/mailman/receiver/imap.rb:49:in `connect'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/mailman-0.7.3/lib/mailman/application.rb:139:in `block in polling_loop'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/mailman-0.7.3/lib/mailman/application.rb:137:in `loop'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/mailman-0.7.3/lib/mailman/application.rb:137:in `polling_loop'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/mailman-0.7.3/lib/mailman/application.rb:81:in `run'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/mailman-0.7.3/lib/mailman/application.rb:15:in `run'
/home/arjen/facebook.loish.net/lib/tasks/run_mailman.rake:11:in `block (2 levels) in <top (required)>'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/arjen/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/bin/rake:23:in `load'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/bin/rake:23:in `<main>'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/bin/ruby_executable_hooks:15:in `eval'
/home/arjen/.rvm/gems/ruby-2.3.3@helpy/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => helpy:mailman

```
Also polling looks disabled now? 

Thanks

**Comment by scott** [comment]
I finally got back to this and confirmed it is working perfectly using gmail IMAP, and sending through gmail SMTP.  I am not sure about the error you are seeing- is that your own mail server, or a service?

I did alter the polling behavior to make it more customizable.  Use this syntax:

`bundle exec rake helpy:mailman mail_interval=60` to poll every 60 seconds.

I prefer to use cron rather than have to monitor another process, which is why i did that change.

**Pull request closed without merging**
