### PR TITLE
Fix strange behaviour in last activities inside posts

### PR DESCRIPTION
**Pull request by Rynaro**
I don't know if anyone notice a strange behaviour inside the list posts. Everytime that anyone inside Helpy reply a message, the activity time calculated is the same of the 'first' post.
Check my screenshots to more explanation:

Here the older code:
timeline1

The fix:
timeline2

---
Seems strange to me this behaviour, and the fix, is so simple. But I don't know if this solution is inside the Helpy code metrics. :blush:

### CODE REVIEW

**Comment by scott** [comment]
Thanks for this @Rynaro, I need to try and remember why I did it that way in the first place, clearly it was "intentional" :)  But if I can't see any good reason I will certainly merge your in, it seems to make more sense.

**Comment by Rynaro** [comment]
I've added a commit adjusting the private message list, in tickets. In CSS, we have `height: 25px`, if a ticket/post with a big title is marked as private, this ticket will overlaps others tickets/posts title below.
Example, in portuguese we have a lot of words, and our grammar is so complicated, and these factors resulting in big titles in most of cases.
I only fix this "problem" replacing height property to margin property.

**Comment by scott** [comment]
@Rynaro can you post a screenshot of the change?  Interesting challenge with internationalization...

**Comment by Rynaro** [comment]
For sure!
Here's a example. I've wroten titles in english, but with these images you can have an idea about this "design issue".
`height: 25px;` image:
discussions_height_issue1
`margin-bottom: 7px;` image (fix candidate):
discussions_height_issue

**Comment by scott** [comment]
Oh, now I totally see what you are referring to!  Thanks for that little UX enhancement!

**Pull request merged**
