### PR TITLE
Android Support

### PR DESCRIPTION
**Pull request by trevormerritt**
Adds QR code, API Endpoints.

Please Squash on merge.  1 is to fix a pair of vulnerable gems.  1 is to revert to default config from my dev environment.

### CODE REVIEW

**Comment by scott** [comment]
@trevormerritt  Remind me, what is the QR code stuff for?  The API endpoints look good, I would probably cherry-pick them into a new PR.

**Comment by trevormerritt** [comment]
When adding an Android client, typing a long API key sucks. The QR code has the URL of the API and the API key. 
The client I've been writing does this now.

**Comment by scott** [comment]
Closing due to inactivity. Whatever happened with this @trevormerritt ?

**Comment by trevormerritt** [comment]
The QR code is so the Android client can use that to enter the API key
rather then a long string of random characters.

**Pull request closed without merging**
