### PR TITLE
Fix/390

### PR DESCRIPTION
**Pull request by SundayAdefila**
This PR implements issue #390 by adding the two default date ranges as well as adding a form for picking custom start and end dates. Implementation is as image attached.

additional date ranges

### CODE REVIEW

**Comment by scott** [comment]
Thanks Sunday!  I will get some feedback together for you.

**Comment by scott** [comment]
So I was thinking about the way the date range filter looks and works, and think we would be better  to use this: https://uxsolutions.github.io/bootstrap-datepicker/?markup=component&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=4&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox

Can you also left align the start and end labels on with the same left margin that the other options have?

**Comment by SundayAdefila** [comment]
Okay, looking into that now.

**Comment by SundayAdefila** [comment]
this has been updated now, and rendering as follow: 


screen shot 2016-10-21 at 3 35 04 pm

screen shot 2016-10-21 at 3 01 03 pm

**Pull request merged**
