### PR TITLE
Refactor/topic mailer

### LINKED ISSUE #406: Refactor/rename topic_mailer
This should really be named `post_mailer` since it sends a message to users when an agent replies to them.  Currently Topic.post.last is used when it really should just use a reference to the Post.

### PR DESCRIPTION
**Pull request by scott**
Fixes #406

### CODE REVIEW

**Comment by CGA1123** [comment]
I might have some changes that could be merged in with this PR at [CGA1123:helpy/refactor-mailer](https://github.com/CGA1123/helpy/tree/refactor-mailer)

**Comment by scott** [comment]
Hmm do you know if its possible to diff this in GitHub?

**Comment by CGA1123** [comment]
Yep! [Here](https://github.com/helpyio/helpy/compare/master...CGA1123:refactor-mailer?diff=split&expand=1&name=refactor-mailer)

**Comment by scott** [comment]
My PR is a little different than your refactoring- it actually moves the mailer from the `Topic` to the `Post` model, eliminating a race condition caused by using `Topic.post.last` when it should reference the `Post` by ID.

However, your refactoring looks awesome, submit a PR with it if you haven't yet.

**Comment by CGA1123** [comment]
Have done! #445

**Pull request merged**
