### PR TITLE
Implement the `User#active` behaviour

### LINKED ISSUE #476: Inactiveting users
Is the 'Active' checkbox working? 
I tried to set off but it doesn't seems to work. The checkbox is unchecked and in the database the users column 'active' is set as false but the user is still able to log in.

### PR DESCRIPTION
**Pull request by CGA1123**
Only `active` users should be allowed to sign in.

Overrides the `Devise::SessionsController#create` action, checks if a user is active, signs them back out if they are not.

Closes #476

### CODE REVIEW

**Comment by scott** [comment]
This looks great, could you write a test spec to cover the active thing? looks like we never had one before.

**Comment by CGA1123** [comment]
Yep will do.

**Comment by CGA1123** [comment]
Added some basic tests, ideally I would want to check that `current_user` is nil when a inactive user tries to sign in, but I can't seem to find a way to actually have access to that method within the tests... 

It's not a huge problem though.

**Comment by scott** [comment]
@CGA1123 Sorry this took so long, I finally got to UAT on this and discovered a couple problems that will be easy to fix:

- If a user is inactive, they should not be able to reset their password.  Currently they can reset password and regain access to their account.
- If a user is an admin and has active API keys, we need to scope the api access by user activity.

Can you work on these and add tests?

**Comment by CGA1123** [comment]
No worries, will have a look at those changes over the coming days!

Sent from my iPhone

On 20 Jan 2017, at 21:59, Scott Miller <notifications@github.com<mailto:notifications@github.com>> wrote:


@CGA1123<https://github.com/CGA1123> Sorry this took so long, I finally got to UAT on this and discovered a couple problems that will be easy to fix:

  *   If a user is inactive, they should not be able to reset their password. Currently they can reset password and regain access to their account.
  *   If a user is an admin and has active API keys, we need to scope the api access by user activity.

Can you work on these and add tests?

-

**Comment by CGA1123** [comment]
@scott sorry for the delay. Uni work is piling up!

Had a look at the reset password case. The reason they are being allowed to log in after a reset is most likely because the devise option [`Devise.sign_in_after_reset_password`](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/passwords_controller.rb#L37) is set to true. Setting this to false in `initializers/devise.rb` could be a quick fix, but would require a user to sign in again after resetting their password. 

If not I can just create a custom controller.

**Comment by scott** [comment]
Good catch, I didn't think about that config setting.  Easy fix :)

**Comment by CGA1123** [comment]
The only disadvantage to that would be that it is easily changed and explicitly forced behaviour by the application!

**Comment by neliojrr** [comment]
Hi! I was looking at devise documentation and I found this 2 methods `active_for_authentication?` and `inactive_message`:
http://www.rubydoc.info/github/plataformatec/devise/Devise/Models/Authenticatable

Maybe it's a good way to solve this overriding this methods in User model doing something like this:
https://github.com/plataformatec/devise/wiki/How-To:-Customize-user-account-status-validation-when-logging-in

What do you guys think?

**Comment by CGA1123** [comment]
@neliojrr Looks very promising! Would be a much cleaner implementation, nice find!

**Comment by neliojrr** [comment]
I commit the code.. take a look: https://github.com/helpyio/helpy/pull/549

**Comment by CGA1123** [comment]
Closing this in favour of #549! @scott

**Pull request closed without merging**
