### PR TITLE
Google OAuth callback name fix

### LINKED ISSUE #666: Google oauth not working
Hi. I have fresh install, trying to set-up google sign-in.
I added omniauth provider at settings.yml
```
omniauth:
  providers:
     google_oauth2:
       id: xx
       secret: xx
```
But after signing in it redirects to 404 page:
> 10.10.0.1 - - [11/Jul/2017:04:28:43 -0400] "GET /users/auth/google_oauth2/callback?state=c9d5ef83c8e25476762e990ec8b9a1c014719c4es3c80075&code=4/TCk466p9xApsHTifXxpU_V0IphaB8WfAsqJis1uQCwE HTTP/1.1" 404 2572 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" "-"

And shows: Nothing was found at this address...

What could be an issue? The request processes fine, it just looks like Helpy doesn't handle such URL.

### PR DESCRIPTION
**Pull request by kobim**
Fixes #666 - the callback name for Google was wrong.

### CODE REVIEW

**Comment by scott** [comment]
Thanks for spotting this @kobim there is not good/or no test overage around the oauth logins, would you be willing to add that?

**Comment by kobim** [comment]
@scott you got it.
(I only added tests to make sure the redirect and callback urls are set correctly, as `omniauth` and its strategy libraries have their own tests)

**Comment by jkloian** [comment]
When will this be merged?  google oauth is broken without it.

**Comment by PNCAcsheridan** [comment]
Thanks for the work @kobim. That got Google oauth2 working for me. Hopefully merged to master soon.

**Comment by lubo** [comment]
@scott What's preventing you from merging this one?

**Pull request merged**
