### PR TITLE
[WIP] Configure OpenShift

### PR DESCRIPTION
**Pull request by olliebennett**
The QuickStart I created:
https://hub.openshift.com/quickstarts/298-helpy

Deploy link for the QuickStart (which the button would link to):
https://hub.openshift.com/quickstarts/deploy/298-helpy

I'm currently having problems with the deployment (seems hard to debug without the full logs) but will try again later. Not sure what will be involved to get it fully working, but it seems to be getting quite far.

### CODE REVIEW

**Comment by olliebennett** [comment]
Next issue:

```
Your Ruby version is 2.0.0, but your Gemfile specified 2.2.1
```

... for now I've removed the ruby version lock from `Gemfile`, because later Ruby versions are not yet supported. [This page](https://www.openshift.com/features/cartridges.html) suggests that `Ruby 2.0.0` is "Online (Next Gen)" which is promising, although there seems to be no cartridge available named `ruby-2.2`...

**Comment by olliebennett** [comment]
We need to make a decision about which version of the OpenShift platform we want to use.

The legacy version (v2?) seems to be the default; examples are for [Rails 4](https://github.com/openshift/rails4-example) (or [Rails 3](https://github.com/openshift/rails-example)), and it's almost working, although the Ruby version is locked to 2.0 (and unlikely to be updated to 2.2 on the legacy platform I would assume).

The new (containerised) version (v3?) has a Rails 4 example [here](https://github.com/openshift/rails-ex), but seems more complicated to manage, and certainly seems more complicated to set up initially, and I don't see any reference to the "OpenShift Button" idea.

@brianjking do you have any other ideas?

**Comment by olliebennett** [comment]
If OpenShift doesn't meet our needs, we could alternatively create an [AWS Marketplace](https://aws.amazon.com/marketplace) offering, which should be pretty quick for users to get up and running.

**Comment by scott** [comment]
Thanks for digging into this @olliebennett! It seems like their implementation is not quite as easy to work with as Heroku.  We could also create and maintain an "official" openshift branch and try to backport to Ruby 2 but I don't see a lot of value there.

**Pull request closed without merging**
