### PR TITLE
Refactor of tickets table rows, to normalize the layout

### PR DESCRIPTION
**Pull request by Rynaro**
Adjusting the admin table rows layout that PR #320 was broken in same time that fix other sector fo Helpy.

Here is a PR that normalize the layout refactoring some helpers (has a fallback support of use), HTML structure, and adjusting some CSS rules.

I made a new PR, because I made some other changes here.

Here's a screenshot after refactor:
selecao_007

### CODE REVIEW

**Comment by scott** [comment]
I am still seeing some issues- specifically the right column in not right aligned on my end (even though in your screenshot they are) and the lines are still not vertically centered (See attachment.)  I reverted the original PR until we get this sorted.  Can you send a PR that just has the locale switcher change, and then we can work out the formatting in a separate PR?

screen shot 2016-09-17 at 10 34 36 am

**Comment by Rynaro** [comment]
Sure, I will made the language switcher in another PR.

In PR, strange rule detection in your screen, because I maintain the `text-align: right;` rule in CSS.  
I think, the vertical alignment issue is solved in new commit that I've made here. My has conflicts now, but I think, it's because you made a revert on another PR.
See the screenshots below of fixes:
**Admin area -> **
selecao_010
 ** User area -> **
selecao_011

**Comment by Rynaro** [comment]
I've made a commit to adjust my branch able to merge with Helpy, but check the layout style. If the PR has some issues in alignment, please take a screenshot and attach here. :smile:

**Comment by scott** [comment]
Yeah I know the right/left alignment thing seemed strange to me, although I didn't look at the actual cause.  But this was one reason I decided to revert the merge just to get a "fresh" try.  Maybe something got mixed up...

Anyways I will review this later today, I hope.

**Pull request closed without merging**
