### PR TITLE
Helpy IMAP

### LINKED ISSUE #221: imap support
ability to fetch inbound email using imap(s) would be nice

### PR DESCRIPTION
**Pull request by scott**
Finally, IMAP is ready for Helpy.  I have taken the previous work and packaged it as a Rails Engine that you can add to your existing Helpy install, or by getting current with `master`.  This allows users who are not ready or able to upgrade to master to just add the gem instead, or skip the functionality if its not needed.

closes #810 
closes #741
closes #221
closes #179
#148

### CODE REVIEW

**Comment by ddeenniiss** [comment]
Hi, first thanks a lot, it's a very nice feature !

I try to test POP or IMAP, and when i launch rake helpy:mailman i have this error
> 
> I, [2018-10-30T19:01:15.980424 #5268]  INFO -- : Got new message from 'toto@test.net' with subject 'test3'.
> #<PG::ConnectionBad: fe_sendauth: no password supplied

**Comment by ddeenniiss** [comment]
same error without SSL for pop and imap.

**Comment by scott** [comment]
Hmmm that looks like a Postgres authentication error- not sure why you would be getting that.  Are you able to access and browse Helpy normally?  Is this in production or dev?

**Comment by ddeenniiss** [comment]
Yes, it's on production and i can access Helpy normally.

when i launch rake helpy:mailman

> I, [2018-11-03T10:47:24.370438 #17396]  INFO -- : Mailman v0.7.3 started
> I, [2018-11-03T10:47:24.370521 #17396]  INFO -- : IMAP receiver enabled (support@xx.net@mail.xx.net).
> I, [2018-11-03T10:47:24.394184 #17396]  INFO -- : Polling disabled. Checking for messages once.
> I, [2018-11-03T10:47:24.986242 #17396]  INFO -- : Got new message from 'denis@xx.net' with subject 'test45'.
> The PGconn, PGresult, and PGError constants are deprecated, and will be
> removed as of version 1.0.
> 
> You should use PG::Connection, PG::Result, and PG::Error instead, respectively.
> 
> Called from /home/rails/.rvm/gems/ruby-2.4.4@helpy/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
> #<PG::ConnectionBad: fe_sendauth: no password supplied
> >
>

**Comment by ddeenniiss** [comment]
Also when i launch rails s -e production -b xxx-p 3000
=> Booting WEBrick
=> Rails 4.2.10 application starting in production on http://xxx:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /home/rails/.rvm/gems/ruby-2.4.4@helpy/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'

**Comment by ddeenniiss** [comment]
Any ideas ?
I follow this doc to install helpy https://github.com/helpyio/helpy/wiki/WIP-Install-on-18.04

**Comment by hadifarnoud** [comment]
it does not work in Docker. I tried everything. did anyone test it on Docker?

**Pull request merged**
