### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by ellimist**

### CODE REVIEW

**Comment by ellimist** [comment]
Anyone knows how this small text fix could break a completely unrelated test?

**Comment by CGA1123** [comment]
@ellimist not sure, having a look at it right now.

**Comment by CGA1123** [comment]
@ellimist 

I think it's because the test relies on the ordering of the response, and the parsing of the JSON response.

In theory the `Hash` data structure is order independent, which would mean that this test can fail trivially. (Not sure tough, need to dig a bit more)

Either way, it isn't your change that caused it.

**Comment by ellimist** [comment]
Yeah, that's what I thought too. Can you try to re-trigger the build job?

**Comment by ellimist** [comment]
Closing and re-opening the pull-request did the trick too 👍  Let's see if the tests pass this time

**Comment by CGA1123** [comment]
Strange, maybe there's something else going on...

**Comment by ellimist** [comment]
@CGA1123 but you were right, the order of the keys is screwing up the tests. The first one failed cause `note` was expected to equal `first`, the second on failed because `note` was expected to equal `reply`.

**Comment by CGA1123** [comment]
@ellimist Ahh well spotted!

**Comment by CGA1123** [comment]
@ellimist Well spotted! Can you open an issue regarding this?

**Comment by scott** [comment]
Yeah this failing test thing has been around for a while.  It only seems to happen once in a while...

**Comment by scott** [comment]
Magically reran the build and its green :)

**Pull request merged**
