### PR TITLE
Remove GitHub link from `config` gem

### LINKED ISSUE #764: Could not find gem 'config (~> 1.1.0)' in https://github.com/railsconfig/config.git (at master@4265c6d).
Trying a non-Docker local install with Ruby 2.4.3:

```
% bundle install
Fetching https://github.com/railsconfig/config.git
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/..
Could not find gem 'config (~> 1.1.0)' in https://github.com/railsconfig/config.git (at master@4265c6d).
The source contains 'config' at: 1.6.0
```

### PR DESCRIPTION
**Pull request by CGA1123**
Closes #764

### CODE REVIEW

**Comment by johnknapp** [comment]
I removed this config gem git link in my dev env and rebuilt lockfile. Afterwards, I encountered a new error (running latest helpy master branch.)

```
remote: -----> Detecting rake tasks
remote: sh: 2: Syntax error: Unterminated quoted string
remote: sh: 2: Syntax error: Unterminated quoted string
remote:  !
remote:  !     Could not detect rake tasks
remote:  !     ensure you can run `$ bundle exec rake -P` against your app
remote:  !     and using the production group of your Gemfile.
remote:  !     rake aborted!
remote:  !     LoadError: cannot load such file -- kaminari/grape
```

Running rake -P in dev env gives same kaminari/grape error.

**Comment by CGA1123** [comment]
Running latest master 397f918c1bb69c27dee789737826fed3fc0424e6 w/ runs `bundle exec rake -P` fine for me (using ruby 2.4.1 and 2.3.3).

Did you run `bundle update` or `bundle install` after editing your Gemfile?

**Comment by johnknapp** [comment]
@CGA1123 Hey Christian, I worked through a handful of issues the other day, not all related to git link on config. I'm on Heroku so have rails_12factor in my prod group. That gem has two dependencies - this is from my lockfile:
```
    rails_12factor (0.0.3)
      rails_serve_static_assets
      rails_stdout_logging
    rails_serve_static_assets (0.0.5)
    rails_stdout_logging (0.0.5)
```

Anyway, I did a test just now, with a stable bundle (including config git link) I removed config gem git link and `bundle install` gave me an error:

```
$ bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies........
Bundler could not find compatible versions for gem "uniform_notifier":
  In snapshot (Gemfile.lock):
    uniform_notifier (= 1.9.0)

  In Gemfile:
    bullet was resolved to 5.7.0, which depends on
      uniform_notifier (~> 1.10.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

Not sure what else to tell you other than I recommend you test with rails_12factor in the mix.

**Comment by CGA1123** [comment]
@johnknapp It seems your bundle has updated the version of `bullet` (from `5.0.0` -> `5.7.0`) and not it's dependencies (`uniform_notifier`).

Editing your Gemfile to explicitly set the version for `bullet` should clear this up.

Alternatively `bundle update bullet` or `bundle update uniform_notifier` should also clear this up.

The `rails_12factor` gem *shouldn't* be affecting that last issue (there are no dependencies between these gems).

**Pull request merged**
