### PR TITLE
Reply and close feature

### PR DESCRIPTION
**Pull request by shaktik1989**
Implementation of https://github.com/helpyio/helpy/issues/197, please have a look and let me know your thoughts.

Thanks!

### CODE REVIEW

**Comment by olliebennett** [comment]
The code looks good. The only improvement could potentially be a separate button for "Reply & Close" alongside "Reply" (as that makes this feature one-click). That would (of course) involve some JavaScript to set your "resolved" flag and the controller would not change. Either way, this feature looks good-to-go!

**Comment by arrowcircle** [comment]
@olliebennett JS is not necessary. You can put custom submit parameter on the button and put resolved flag in the controller

**Comment by olliebennett** [comment]
Sorry, deleted my previous comment:

> The code looks good. The only improvement could potentially be a separate button for "Reply & Close" alongside "Reply" (as that makes this feature one-click). That would (of course) involve some JavaScript to set your "resolved" flag and the controller would not change. This could be saved for a future improvement. Either way, this feature looks good-to-go!

If it's easy to do then that might be a smoother UX, but this PR is an improvement as-is regardless.

**Comment by scott** [comment]
My thoughts:  @olliebennett I went back and forth on whether a button or a checkbox was a better experience just because it is too easy to click the wrong button. Yes the checkbox adds a step, but it forces a conscious decision. I think it really depends how often you will both reply and close at the same time.  A future enhancement I have in mind is an "autoclose after N number of days" so old messages get handled automatically which further reduces the need to "reply and close".

**Comment by scott** [comment]
@shaktik1989 Looks good, one thing I noticed is that the stat boxes at the top don't update when the message is marked resolved (ie. the resolved count should +1 and the corresponding counter should decrease by one).  You may just be missing the `get_counts` invocation which refreshes the stats or just didn't refresh that part of the page?

**Pull request merged**
