### PR TITLE
Update Japanese messages.

### PR DESCRIPTION
**Pull request by monaka**

### CODE REVIEW

**Comment by Rynaro** [comment]
Has something wrong in line 62 that breaks the YAML schema. Travis can't read your code because of this.
Adjust the key parsing error, and I think Travis build will be successful. :)

**Comment by monaka** [comment]
@Rynaro Thanks for your advice.
The build failure was caused a multi-byte white space. I forgot to check before committing it. 
I fixed there and force-pushed. Please check it again.

**Comment by monaka** [comment]
Added some more traslations.

**Comment by scott** [comment]
Awesome, thanks for providing these updates!

**Pull request merged**
