### PR TITLE
[WIP] Update 'devise' gem (again)

### PR DESCRIPTION
**Pull request by olliebennett**
Devise > 4.0.0 supports Rails 5.

Apologies for [previous PR](https://github.com/helpyio/helpy/pull/236) updating directly to Devise 4.2 (which was [reverted](https://github.com/helpyio/helpy/pull/241)).

There are some other issues with updating devise which I'll also try and address here before we merge it. If I can get some testing around the failing call to `user_omniauth_authorize_path` within `login_with` (in `application_helper.rb`), then I will do. Refactoring that would allow us to update beyond Devise 4.0 too...

### CODE REVIEW

**Comment by scott** [comment]
@olliebennett is this still WIP or should it be merged?

**Comment by olliebennett** [comment]
It's WIP because I've not yet confirmed that "login with X" still works - I need to set up those keys in my environment which is holding me up.

**Comment by connorshea** [comment]
@olliebennett @scott are there not tests for "Login with X"?

**Comment by scott** [comment]
No there are not :(

**Comment by scott** [comment]
See #992 Updating to 4 is causing problems with a change in oauth helpers.  Closing this for now.

**Pull request closed without merging**
